package aularevisao.gui.cadastro;

import aularevisao.dao.FabricanteDAO;
import aularevisao.dao.ModeloDAO;
import aularevisao.entity.Fabricante;
import aularevisao.entity.Modelo;
import java.util.List;
import javax.swing.JFrame;

public class CadastroModeloGUI extends javax.swing.JDialog {

    private ModeloDAO dao = new ModeloDAO();
    private CadastroModeloEditarGUI editarDialog;

    public CadastroModeloGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        editarDialog = new CadastroModeloEditarGUI((JFrame) this.getParent(), true, null);

        BasicCrudPANEL panelConsulta = new BasicCrudPANEL<>(dao, editarDialog);
        panelConsulta.carregarLista(getDadosLista(), getColunasLista());
        
        panelConsultaModelo.add(panelConsulta);
    }

    public Object[][] getDadosLista() {
        List<Modelo> listaModelo = dao.select();

        Object[][] dados = new Object[listaModelo.size()][3];

        int i = 0;

        for (Modelo modelo : listaModelo) {
            dados[i][0] = modelo.getId();
            dados[i][1] = modelo.getNome();
            dados[i][2] = modelo.getId_fabricante();

            i++;
        }

        return dados;
    }

    public Object[] getColunasLista() {
        return new Object[]{"ID", "NOME", "ID FABRICANTE"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        panelConsultaModelo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        panelConsultaModelo.setLayout(new javax.swing.BoxLayout(panelConsultaModelo, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 432, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addComponent(panelConsultaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JPanel panelConsultaModelo;
    // End of variables declaration//GEN-END:variables
}
